#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#
set -e

printf "⏳ Loading context data "

#
# Create Companies Entities
#
curl -s -o /dev/null -X POST \
  'http://orion:'$ORION_PORT'/v2/entities' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: openiot' \
  -H 'fiware-servicepath: /' \
  -d '{
      "id": "urn:ngsi-ld:Store:001",
      "type": "Store",
      "address": {
            "type": "PostalAddress",
            "value": {
                  "streetAddress": "Paseo de Miramón 170",
                  "addressRegion": "Gipuzkoa",
                  "addressLocality": "Donostia",
                  "postalCode": "20014"
            }
      },
      "location": {
            "type": "geo:json",
            "value": {
                  "type": "Point",
                  "coordinates": [
                        12.3986,
                        50.5547
                  ]
            }
      },
      "name": {
            "type": "Text",
            "value": "Remote Monitoring Services"
      }
}'

echo -e " \033[1;32mdone\033[0m"