{
 "title": "cschenum_cseqnum",
 "time": { "from": "2022-05-05T11:59:59.000Z", "to": "2022-05-06T03:59:55.000Z" },
 "panels": [
  {
   "title": "RM2FM Process Control",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT avg(time_index) as time,SUM(case when ABS(CAST(rm2fm as double)-CAST(fmxwide as double)) > 0.9939 THEN 1.00 else 0.00 end)/100 as fraccion_defectuosa from \"doc\".\"etmodelorm\" group by (cschenum_cseqnum-1)/100 order by time;\n"
    }
   ]
  },
  {
   "title": "LBO2FM Process control ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT avg(time_index) as time,SUM(case when ABS(CAST(lbo2fm as double)-CAST(fmxwide as double)) > 2.781 THEN 1.00 else 0.00 end)/100 as fraccion_defectuosa from \"doc\".\"etmodelolbo\" group by (cschenum_cseqnum-1)/100 order by time;\n"
    }
   ]
  },
  {
   "title": "Total coils",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time_index as time, cschenum_cseqnum FROM \"doc\".\"etlbo\" WHERE entity_id='urn:ngsi-ld:Lbo:001' GROUP BY time, cschenum_cseqnum ORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Coils timestamp",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT fmxwide,lbo2fm,cschenum_cseqnum  FROM \"doc\".\"etmodelolbo\" ORDER BY cschenum_cseqnum ASC"
    },
    {
     "rawSql": "SELECT rm2fm, cschenum_cseqnum FROM \"doc\".\"etmodelorm\" ORDER BY cschenum_cseqnum ASC\n"
    },
    {
     "rawSql": "SELECT case when ABS(CAST(rm2fm as double)-CAST(fmxwide as double)) > 0.9939 THEN 'WARNING' else 'OK' end as Warning_RM,cschenum_cseqnum  FROM \"doc\".\"etmodelorm\" ORDER BY cschenum_cseqnum ASC\n"
    },
    {
     "rawSql": "SELECT case when ABS(CAST(lbo2fm as double)-CAST(fmxwide as double)) > 2.781 THEN 'WARNING' else 'OK' end as Warning_LBO,cschenum_cseqnum  FROM \"doc\".\"etmodelolbo\" ORDER BY cschenum_cseqnum ASC\n"
    }
   ]
  }
 ]
}